branch-defaults:
  master:
    environment: $CIRCLE_BRANCH-openbook-us-api
global:
  application_name: openbook-us-api
  default_ec2_keyname: null
  default_platform: python-3.6
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
